server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cdh951102!
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create(실행할때마다 생성) 추후에 업데이트로 변경 update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #테이블을 만들때 변수명 그대로 db에 필드를 넣어준다 #SpringPhysiclaNamingStrategy를 사용하면
      use-new-id-generator-mappings: false #jpa가 사용하는 기본 넘버링 전략을 따라가지 않는다
    show-sql: true #콘솔창에 sql문 보여주는 기능
    properties: #정렬해서 콘솔창에 보여준다
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
      
      